# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgentTask.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Team_pb2 as Team
from . import ProductColor_pb2 as ProductColor


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x41gentTask.proto\x12\tllsf_msgs\x1a\nTeam.proto\x1a\x12ProductColor.proto\"\xfb\x03\n\tAgentTask\x12#\n\nteam_color\x18\x01 \x02(\x0e\x32\x0f.llsf_msgs.Team\x12\x0f\n\x07task_id\x18\x02 \x02(\r\x12\x10\n\x08robot_id\x18\x03 \x02(\r\x12\x1d\n\x04move\x18\x04 \x01(\x0b\x32\x0f.llsf_msgs.Move\x12%\n\x08retrieve\x18\x05 \x01(\x0b\x32\x13.llsf_msgs.Retrieve\x12#\n\x07\x64\x65liver\x18\x06 \x01(\x0b\x32\x12.llsf_msgs.Deliver\x12(\n\x06\x62uffer\x18\x07 \x01(\x0b\x32\x18.llsf_msgs.BufferStation\x12\x33\n\x0f\x65xplore_machine\x18\x08 \x01(\x0b\x32\x1a.llsf_msgs.ExploreWaypoint\x12>\n\x15workpiece_description\x18\t \x01(\x0b\x32\x1f.llsf_msgs.WorkpieceDescription\x12\x10\n\x08order_id\x18\n \x01(\r\x12\x13\n\x0b\x63\x61ncel_task\x18\x0b \x01(\x08\x12\x12\n\npause_task\x18\x0c \x01(\x08\x12\x12\n\nsuccessful\x18\r \x01(\x08\x12\x10\n\x08\x63\x61nceled\x18\x0e \x01(\x08\x12\x12\n\nerror_code\x18\x0f \x01(\r\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xc0>\x12\r\n\x08MSG_TYPE\x10\xf6\x03\"/\n\x04Move\x12\x10\n\x08waypoint\x18\x01 \x02(\t\x12\x15\n\rmachine_point\x18\x02 \x01(\t\"5\n\x08Retrieve\x12\x12\n\nmachine_id\x18\x01 \x02(\t\x12\x15\n\rmachine_point\x18\x02 \x02(\t\"4\n\x07\x44\x65liver\x12\x12\n\nmachine_id\x18\x01 \x02(\t\x12\x15\n\rmachine_point\x18\x02 \x02(\t\"9\n\rBufferStation\x12\x12\n\nmachine_id\x18\x01 \x02(\t\x12\x14\n\x0cshelf_number\x18\x02 \x02(\r\"N\n\x0f\x45xploreWaypoint\x12\x12\n\nmachine_id\x18\x01 \x02(\t\x12\x15\n\rmachine_point\x18\x02 \x02(\t\x12\x10\n\x08waypoint\x18\x03 \x02(\t\"\xbc\x01\n\x14WorkpieceDescription\x12(\n\nbase_color\x18\x03 \x02(\x0e\x32\x14.llsf_msgs.BaseColor\x12)\n\x0bring_colors\x18\x04 \x03(\x0e\x32\x14.llsf_msgs.RingColor\x12&\n\tcap_color\x18\x05 \x01(\x0e\x32\x13.llsf_msgs.CapColor\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xc0>\x12\r\n\x08MSG_TYPE\x10\xfe\x03\x42\x33\n\x1forg.robocup_logistics.llsf_msgsB\x10\x41gentTasksProtos')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AgentTask_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\020AgentTasksProtos'
  _globals['_AGENTTASK']._serialized_start=63
  _globals['_AGENTTASK']._serialized_end=570
  _globals['_AGENTTASK_COMPTYPE']._serialized_start=531
  _globals['_AGENTTASK_COMPTYPE']._serialized_end=570
  _globals['_MOVE']._serialized_start=572
  _globals['_MOVE']._serialized_end=619
  _globals['_RETRIEVE']._serialized_start=621
  _globals['_RETRIEVE']._serialized_end=674
  _globals['_DELIVER']._serialized_start=676
  _globals['_DELIVER']._serialized_end=728
  _globals['_BUFFERSTATION']._serialized_start=730
  _globals['_BUFFERSTATION']._serialized_end=787
  _globals['_EXPLOREWAYPOINT']._serialized_start=789
  _globals['_EXPLOREWAYPOINT']._serialized_end=867
  _globals['_WORKPIECEDESCRIPTION']._serialized_start=870
  _globals['_WORKPIECEDESCRIPTION']._serialized_end=1058
  _globals['_WORKPIECEDESCRIPTION_COMPTYPE']._serialized_start=1019
  _globals['_WORKPIECEDESCRIPTION_COMPTYPE']._serialized_end=1058
# @@protoc_insertion_point(module_scope)
