# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Pose2D.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Time_pb2 as Time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cPose2D.proto\x12\tllsf_msgs\x1a\nTime.proto\"O\n\x06Pose2D\x12\"\n\ttimestamp\x18\x01 \x02(\x0b\x32\x0f.llsf_msgs.Time\x12\t\n\x01x\x18\x02 \x02(\x02\x12\t\n\x01y\x18\x03 \x02(\x02\x12\x0b\n\x03ori\x18\x04 \x02(\x02\x42/\n\x1forg.robocup_logistics.llsf_msgsB\x0cPose2DProtos')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Pose2D_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\014Pose2DProtos'
  _globals['_POSE2D']._serialized_start=39
  _globals['_POSE2D']._serialized_end=118
# @@protoc_insertion_point(module_scope)
