# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProductColor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ProductColor.proto\x12\tllsf_msgs*L\n\tRingColor\x12\r\n\tRING_BLUE\x10\x01\x12\x0e\n\nRING_GREEN\x10\x02\x12\x0f\n\x0bRING_ORANGE\x10\x03\x12\x0f\n\x0bRING_YELLOW\x10\x04*J\n\tBaseColor\x12\x0c\n\x08\x42\x41SE_RED\x10\x01\x12\x0e\n\nBASE_BLACK\x10\x02\x12\x0f\n\x0b\x42\x41SE_SILVER\x10\x03\x12\x0e\n\nBASE_CLEAR\x10\x04*\'\n\x08\x43\x61pColor\x12\r\n\tCAP_BLACK\x10\x01\x12\x0c\n\x08\x43\x41P_GREY\x10\x02\x42\x35\n\x1forg.robocup_logistics.llsf_msgsB\x12ProductColorProtos')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProductColor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\022ProductColorProtos'
  _globals['_RINGCOLOR']._serialized_start=33
  _globals['_RINGCOLOR']._serialized_end=109
  _globals['_BASECOLOR']._serialized_start=111
  _globals['_BASECOLOR']._serialized_end=185
  _globals['_CAPCOLOR']._serialized_start=187
  _globals['_CAPCOLOR']._serialized_end=226
# @@protoc_insertion_point(module_scope)
