# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Team.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nTeam.proto\x12\tllsf_msgs*\x1d\n\x04Team\x12\x08\n\x04\x43YAN\x10\x00\x12\x0b\n\x07MAGENTA\x10\x01\x42-\n\x1forg.robocup_logistics.llsf_msgsB\nTeamProtos')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Team_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\nTeamProtos'
  _globals['_TEAM']._serialized_start=25
  _globals['_TEAM']._serialized_end=54
# @@protoc_insertion_point(module_scope)
