# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Time.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nTime.proto\x12\tllsf_msgs\"!\n\x04Time\x12\x0b\n\x03sec\x18\x01 \x02(\x03\x12\x0c\n\x04nsec\x18\x02 \x02(\x03\x42-\n\x1forg.robocup_logistics.llsf_msgsB\nTimeProtos')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Time_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\nTimeProtos'
  _globals['_TIME']._serialized_start=25
  _globals['_TIME']._serialized_end=58
# @@protoc_insertion_point(module_scope)
